### ISSUE TITLE
中文简历使用tex无法正确编译

### ISSUE THREAD

**Issue by buoyont** [gaocegege/Deedy-Resume-for-Chinese#2]
报错如下：
WARNING ** Failed to load ToUnicode CMap for font "SourceHanSerifSC-ExtraLight"*
* WARNING ** Failed to load ToUnicode CMap for font "SourceHanSerifSC-Bold" *
* WARNING ** Failed to load ToUnicode CMap for font "SourceHanSerifSC-Medium" *
* WARNING ** Failed to load ToUnicode CMap for font "SourceHanSerifSC-Regular" 
** ERROR ** sfnt: Freetype failure... Output file removed

**Comment by gaocegege** [comment]
没有字体吧

**Comment by buoyont** [comment]
我已经在本地下载这几种字体了啊

**Comment by gaocegege** [comment]
需要安装的
